### ISSUE TITLE
Enable tests under Windows on Travis CI

### ISSUE THREAD

**Issue by gplssm** [openego/ding0#299]
PR #294 introduces conda based testing on Travis CI servers. In general, it is implemented such that the current configuration should allow for tests running under windows. This option is commented-out, because the conda installation (or even `conda info --all`) runs into errors:

```
[0K$ conda info --all

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "C:\tools\miniconda3\lib\site-packages\conda\exceptions.py", line 1062, in __call__
        return func(*args, **kwargs)
      File "C:\tools\miniconda3\lib\site-packages\conda\cli\main.py", line 84, in _main
        exit_code = do_call(args, p)
      File "C:\tools\miniconda3\lib\site-packages\conda\cli\conda_argparse.py", line 80, in do_call
        module = import_module(relative_mod, __name__.rsplit('.', 1)[0])
      File "C:\tools\miniconda3\lib\importlib\__init__.py", line 127, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
      File "<frozen importlib._bootstrap>", line 983, in _find_and_load
      File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
      File "<frozen importlib._bootstrap_external>", line 728, in exec_module
      File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
      File "C:\tools\miniconda3\lib\site-packages\conda\cli\main_info.py", line 19, in <module>
        from ..core.index import _supplement_index_with_system
      File "C:\tools\miniconda3\lib\site-packages\conda\core\index.py", line 9, in <module>
        from .package_cache_data import PackageCacheData
      File "C:\tools\miniconda3\lib\site-packages\conda\core\package_cache_data.py", line 15, in <module>
        from conda_package_handling.api import InvalidArchiveError
      File "C:\tools\miniconda3\lib\site-packages\conda_package_handling\api.py", line 3, in <module>
        from libarchive.exception import ArchiveError as _LibarchiveArchiveError
      File "C:\tools\miniconda3\lib\site-packages\libarchive\__init__.py", line 1, in <module>
        from .entry import ArchiveEntry
      File "C:\tools\miniconda3\lib\site-packages\libarchive\entry.py", line 6, in <module>
        from . import ffi
      File "C:\tools\miniconda3\lib\site-packages\libarchive\ffi.py", line 48, in <module>
        libarchive = ctypes.cdll.LoadLibrary(libarchive_path)
      File "C:\tools\miniconda3\lib\ctypes\__init__.py", line 434, in LoadLibrary
        return self._dlltype(name)
      File "C:\tools\miniconda3\lib\ctypes\__init__.py", line 356, in __init__
        self._handle = _dlopen(self._name, mode)
    TypeError: LoadLibrary() argument 1 must be str, not None

`$ C:\tools\miniconda3\Scripts\conda-script.py info --all`


An unexpected error has occurred. Conda has prepared the above report.
```

Interestingly, tests under windows [were running](https://travis-ci.org/openego/ding0/jobs/558847579) at some point (except for tests that were hanging because of other reasons). The configuration for successfully running the tests with conda under windows on Travis CI can be found [here](https://github.com/openego/ding0/commits/feature/travis_tests_in_windows).

**TODOs**

- [ ] Make conda install the ding0 environment 
- [ ] Make sure all tests pass

**Comment by nesnoj** [comment]
Conda support will be dropped #339 and travis CI replaced by GH actions #338
