### ISSUE TITLE
LVLoadArea in grid 938 is not getting connected to the station

### ISSUE THREAD

**Issue by khelfen** [openego/ding0#367]
When trying to generate the grid 938 the following error occurs:

```
Traceback (most recent call last):
  File "/home/kilian/Documents/PythonProjects/ding0_orig/ding0/ding0/examples/example_single_grid_district.py", line 47, in <module>
    nd.run_ding0(session=session,
  File "/home/kilian/Documents/PythonProjects/ding0_orig/ding0/ding0/core/__init__.py", line 336, in run_ding0
    self.run_powerflow(session, method='onthefly', export_pypsa=False, debug=debug)
  File "/home/kilian/Documents/PythonProjects/ding0_orig/ding0/ding0/core/__init__.py", line 1999, in run_powerflow
    grid_district.mv_grid.run_powerflow(method='onthefly',
  File "/home/kilian/Documents/PythonProjects/ding0_orig/ding0/ding0/core/network/grids.py", line 766, in run_powerflow
    components, _,  components_data = fill_mvgd_component_dataframes(self.grid_district, buses_df, generators_df,
  File "/home/kilian/Documents/PythonProjects/ding0_orig/ding0/ding0/tools/pypsa_io.py", line 170, in fill_mvgd_component_dataframes
    fill_component_dataframes(mv_grid, buses_df, lines_df, transformer_df,
  File "/home/kilian/Documents/PythonProjects/ding0_orig/ding0/ding0/tools/pypsa_io.py", line 268, in fill_component_dataframes
    nodes_to_dict_of_dataframes(grid, nodes, buses_df, generators_df,
  File "/home/kilian/Documents/PythonProjects/ding0_orig/ding0/ding0/tools/pypsa_io.py", line 342, in nodes_to_dict_of_dataframes
    raise Exception("{} is isolated node. Please check.".
Exception: LVLoadAreaCentre_mvgd_938_157260 is isolated node. Please check.
```

It seems like one LVLoadArea is not getting connected to the station.

![image](https://user-images.githubusercontent.com/46815982/159849539-5957e750-85af-4f69-8573-ff1cdcd0b78a.png)

**Comment by mltja** [comment]
Obsolete with no grids.
